# Docker Compose for Order Kitchen App
# Works cleanly on any machine without installing PHP, Apache, or PostgreSQL locally

services:
  db:
    image: postgres:15
    container_name: order_kitchen_db
    restart: always
    environment:
      POSTGRES_DB: order_kitchen
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
    ports:
      - "5432:5432"
    volumes:
      # Ensures persistent data and proper permissions
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dbuser -d order_kitchen" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  php:
    build: .
    container_name: order_kitchen_app
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://dbuser:dbpass@db:5432/order_kitchen?serverVersion=15&charset=utf8"
      KITCHEN_CAPACITY: 5
      NEXT_PICKUP_BUFFER: 15
      AUTO_COMPLETE_DELAY: 10

networks:
  default:
    driver: bridge
